# Generated by Django 6.0.1 on 2026-01-21 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('total_blue_fuels', models.IntegerField(default=0)),
                ('total_red_fuels', models.IntegerField(default=0)),
                ('blue_1_auto_fuel', models.IntegerField(default=0)),
                ('blue_2_auto_fuel', models.IntegerField(default=0)),
                ('blue_3_auto_fuel', models.IntegerField(default=0)),
                ('red_1_auto_fuel', models.IntegerField(default=0)),
                ('red_2_auto_fuel', models.IntegerField(default=0)),
                ('red_3_auto_fuel', models.IntegerField(default=0)),
                ('blue_1_teleop_fuel', models.IntegerField(default=0)),
                ('blue_2_teleop_fuel', models.IntegerField(default=0)),
                ('blue_3_teleop_fuel', models.IntegerField(default=0)),
                ('red_1_teleop_fuel', models.IntegerField(default=0)),
                ('red_2_teleop_fuel', models.IntegerField(default=0)),
                ('red_3_teleop_fuel', models.IntegerField(default=0)),
                ('blue_1_fuel_scored', models.IntegerField(default=0)),
                ('blue_2_fuel_scored', models.IntegerField(default=0)),
                ('blue_3_fuel_scored', models.IntegerField(default=0)),
                ('red_1_fuel_scored', models.IntegerField(default=0)),
                ('red_2_fuel_scored', models.IntegerField(default=0)),
                ('red_3_fuel_scored', models.IntegerField(default=0)),
                ('calculated_points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='backend.competition')),
                ('blue_team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_1_matches', to='backend.team')),
                ('blue_team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_2_matches', to='backend.team')),
                ('blue_team_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_3_matches', to='backend.team')),
                ('red_team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_1_matches', to='backend.team')),
                ('red_team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_2_matches', to='backend.team')),
                ('red_team_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_3_matches', to='backend.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_points', models.FloatField(default=0.0)),
                ('tie', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='team_pictures/')),
                ('prescout_drivetrain', models.CharField(blank=True, choices=[('swerve', 'Swerve'), ('tank', 'Tank'), ('mecanum', 'Mecanum'), ('other', 'Other')], max_length=20, null=True)),
                ('prescout_hopper_size', models.IntegerField(blank=True, default=0, null=True)),
                ('prescout_intake_type', models.CharField(blank=True, choices=[('inbumper', 'In Bumper'), ('overbumper', 'Over Bumper')], max_length=20, null=True)),
                ('prescout_rotate_yaw', models.BooleanField(default=False)),
                ('prescout_rotate_pitch', models.BooleanField(default=False)),
                ('prescout_self_reported_accuracy', models.FloatField(blank=True, default=0.0, null=True)),
                ('prescout_unload_time', models.FloatField(blank=True, default=0.0, null=True)),
                ('prescout_range', models.CharField(blank=True, choices=[('alliance', 'Alliance'), ('neutral', 'Neutral'), ('opponent', 'Opponent')], max_length=20, null=True)),
                ('prescout_climber', models.CharField(blank=True, choices=[('l1', 'Level 1'), ('l2', 'Level 2'), ('l3', 'Level 3'), ('none', 'None')], max_length=20, null=True)),
                ('prescout_climber_auto', models.BooleanField(default=False)),
                ('prescout_self_reported_auto_shoot', models.IntegerField(default=0)),
                ('prescout_additional_comments', models.TextField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, default=0.0, null=True)),
                ('avg_fuel_scored', models.FloatField(blank=True, default=0.0, null=True)),
                ('avg_shuttle', models.FloatField(blank=True, default=0.0, null=True)),
                ('avg_auto_fuel', models.FloatField(blank=True, default=0.0, null=True)),
                ('avg_climb_points', models.FloatField(blank=True, default=0.0, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='backend.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='backend.team')),
            ],
            options={
                'ordering': ['-ranking_points'],
                'unique_together': {('team', 'competition')},
            },
        ),
    ]
