# Generated by Django 6.0.1 on 2026-01-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_match_blue_1_climb_match_blue_2_climb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='has_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('qualification', 'Qualification'), ('quarterfinal', 'Quarterfinal'), ('semifinal', 'Semifinal'), ('final', 'Final')], default='Qualification', max_length=20),
        ),
    ]
