# Generated by Django 6.0.1 on 2026-01-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_match_has_played_match_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='set_number',
            field=models.IntegerField(default=1),
        ),
    ]
