# Generated by Django 6.0.1 on 2026-01-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_match_set_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_match_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='predicted_match_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='start_match_time',
            field=models.IntegerField(default=0),
        ),
    ]
