# Generated by Django 6.0.1 on 2026-01-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_match_end_match_time_match_predicted_match_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='offset_stream_time_to_unix_timestamp_day_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='offset_stream_time_to_unix_timestamp_day_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='offset_stream_time_to_unix_timestamp_day_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='stream_link_day_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='stream_link_day_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='stream_link_day_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
