# Generated by Django 6.0.1 on 2026-02-02 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_competition_offset_stream_time_to_unix_timestamp_day_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('traveling', 'Traveling'), ('shooting', 'Shooting'), ('passing', 'Passing'), ('collecting', 'Collecting'), ('defending', 'Defending'), ('disabled', 'Disabled'), ('idle', 'Idle')], max_length=20)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_actions', to='backend.match')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_actions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_actions', to='backend.team')),
            ],
            options={
                'ordering': ['match', 'start_time'],
            },
        ),
        migrations.DeleteModel(
            name='ShotTiming',
        ),
    ]
