# Generated by Django 6.0.1 on 2026-02-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_robotaction_delete_shottiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_auto_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_endgame_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_ranking_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_teleop_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='red_auto_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='red_endgame_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='red_ranking_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='red_teleop_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='red_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='winning_alliance',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('tie', 'Tie')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='robotaction',
            name='action_type',
            field=models.CharField(choices=[('traveling', 'Traveling'), ('shooting', 'Shooting'), ('passing', 'Passing'), ('collecting', 'Collecting'), ('defending', 'Defending'), ('disabled', 'Disabled'), ('idle', 'Idle'), ('climbing', 'Climbing')], max_length=20),
        ),
    ]
