# Generated by Django 6.0.1 on 2026-02-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_match_blue_auto_points_match_blue_endgame_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaminfo',
            options={'ordering': ['-ranking_points', '-avg_alliance_match_points', '-avg_auto_fuel']},
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='avg_alliance_match_points',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
