# Generated by Django 6.0.1 on 2026-02-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_teaminfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaminfo',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
