# Generated by Django 6.0.1 on 2026-02-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_teaminfo_options_teaminfo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='auto_success',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='auto_success_sd',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='avg_points_contributed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='climb_success',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='climb_success_sd',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='consistency_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
