# Generated by Django 6.0.1 on 2026-02-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_robotaction_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='auto_success',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='auto_success_sd',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='avg_alliance_match_points',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='climb_success',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='climb_success_sd',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='prescout_climber',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='prescout_climber_auto',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='prescout_self_reported_accuracy',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='prescout_self_reported_auto_shoot',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='prescout_unload_time',
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='avg_auto_fuel_sd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='avg_climb_points_sd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
