# Generated by Django 6.0.1 on 2026-02-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_teaminfo_auto_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_1_auto_climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_2_auto_climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_3_auto_climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red_1_auto_climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red_2_auto_climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red_3_auto_climb',
            field=models.BooleanField(default=False),
        ),
    ]
