# Generated by Django 6.0.1 on 2026-02-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_match_blue_1_auto_climb_match_blue_2_auto_climb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='avg_fuel_sd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
