# Generated by Django 6.0.1 on 2026-02-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_teaminfo_avg_fuel_sd'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_penalties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='red_penalties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_driver_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='prescout_intake_type',
            field=models.CharField(blank=True, choices=[('inbumper', 'In Bumper'), ('overbumper', 'Over Bumper'), ('dropin', 'Drop In')], max_length=20, null=True),
        ),
    ]
