# Generated by Django 6.0.1 on 2026-02-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_match_blue_penalties_match_red_penalties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
