# Generated by Django 6.0.1 on 2026-02-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_change_picture_to_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotaction',
            name='fuel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotaction',
            name='is_playoff',
            field=models.BooleanField(default=False),
        ),
    ]
