# Generated by Django 6.0.1 on 2026-02-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_add_robot_action_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='video_available',
            field=models.BooleanField(default=False),
        ),
    ]
