# Generated by Django 6.0.1 on 2026-02-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_match_video_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='first_match_video_position_day_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='first_match_video_position_day_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='first_match_video_position_day_3',
            field=models.IntegerField(default=0),
        ),
    ]
