# Generated by Django 6.0.1 on 2026-02-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_add_first_match_video_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='video_clipped',
            field=models.BooleanField(default=False),
        ),
    ]
