# Generated by Django 6.0.1 on 2026-03-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_add_video_clipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fuel_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
