# Generated by Django 6.0.1 on 2026-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_match_fuel_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotaction',
            name='action_type',
            field=models.CharField(choices=[('traversing', 'Traversing'), ('shooting', 'Shooting'), ('defending', 'Defending'), ('intake', 'Intake'), ('outtake', 'Outtake'), ('herding', 'Herding'), ('disabled', 'Disabled'), ('climbing', 'Climbing')], max_length=20),
        ),
    ]
