# Generated by Django 6.0.1 on 2026-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_robotaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='skip_processing',
            field=models.BooleanField(default=False),
        ),
    ]
