# Generated by Django 6.0.1 on 2026-04-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_match_skip_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_shooter_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_trench_travel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_trench_travel_preference',
            field=models.CharField(blank=True, choices=[('trench', 'Trench'), ('bump', 'Bump'), ('both', 'Both')], max_length=20, null=True),
        ),
    ]
