# Generated by Django 6.0.1 on 2026-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_teaminfo_prescout_shooter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='prescout_intake_type',
            field=models.CharField(blank=True, choices=[('inbumper', 'In Bumper'), ('overbumper', 'Over Bumper'), ('dropin', 'Drop In'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='prescout_shooter_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('none', 'None')], max_length=20, null=True),
        ),
    ]
