# Generated by Django 6.0.1 on 2026-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_teaminfo_prescout_intake_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='prescout_range',
            field=models.CharField(blank=True, choices=[('alliance', 'Alliance'), ('neutral', 'Neutral'), ('opponent', 'Opponent'), ('none', 'None')], max_length=20, null=True),
        ),
    ]
