# Generated by Django 6.0.1 on 2026-04-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_teaminfo_prescout_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_auto_center_sweeps',
            field=models.CharField(blank=True, choices=[('na', 'Not Applicable'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_auto_climb_level',
            field=models.CharField(blank=True, choices=[('none', 'No Climb'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_auto_crosses_center_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_auto_depot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_auto_outpost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_auto_starting_pose',
            field=models.CharField(blank=True, choices=[('bump', 'Bump'), ('trench', 'Trench'), ('either', 'Either')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_has_auto',
            field=models.BooleanField(default=False),
        ),
    ]
