# Generated by Django 6.0.1 on 2026-04-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_teaminfo_prescout_auto_center_sweeps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='prescout_has_disruption_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='prescout_auto_starting_pose',
            field=models.CharField(blank=True, choices=[('bump', 'Bump'), ('trench', 'Trench'), ('either', 'Either'), ('na', 'N/A')], max_length=20, null=True),
        ),
    ]
