# Generated by Django 6.0.1 on 2026-04-09 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_teaminfo_prescout_has_disruption_auto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
