"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from root .env file
ROOT_DIR = BASE_DIR.parent
load_dotenv(ROOT_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-tsypkgno@k@b&jw*u(_ccsw4r712f_93w5kj)1y1p0mi7l(rlp"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "8000--main--django-playground--aviator2277.chargingcourses.com",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "django_q",  # Django Q2 for background tasks
    "backend",
    "dev_commands",  # Development management commands
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # Compress responses
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional locations of static files
STATICFILES_DIRS = [
    ROOT_DIR / "frontend" / "dist",  # Expo web build output
]

# Media files (User-uploaded content)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# CORS Configuration
# For development: Allow all origins
# For production: Uncomment CORS_ALLOWED_ORIGINS and add your production domains
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        "http://8000--main--django-playground--aviator2277.chargingcourses.com",
        "https://8000--main--django-playground--aviator2277.chargingcourses.com",
        "https://www.yourdomain.com",
        # Add your production frontend URLs here
    ]

CORS_ALLOW_CREDENTIALS = True

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "backend.tasks": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "backend.schedule_setup": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Django Q2 Configuration
# BACKGROUND_DEV determines if tasks run asynchronously (False/prod) or synchronously (True/dev)
# When True (dev mode), tasks run immediately in the same process without needing qcluster
# When False (prod mode), tasks are queued and require running `python manage.py qcluster`
BACKGROUND_DEV = os.getenv("BACKGROUND_DEV", "true").lower() == "true"

Q_CLUSTER = {
    "name": "VibeScout",
    "workers": int(os.getenv("DJANGO_Q_WORKERS", "4")),  # Number of worker processes
    "recycle": 500,  # Recycle worker after this many tasks
    "timeout": int(
        os.getenv("DJANGO_Q_TIMEOUT", "300")
    ),  # Task timeout in seconds (5 minutes)
    "retry": int(
        os.getenv("DJANGO_Q_RETRY", "360")
    ),  # Retry failed tasks after this many seconds (6 minutes)
    "queue_limit": 50,  # Maximum tasks in queue
    "bulk": 10,  # Number of tasks to process in bulk
    "orm": "default",  # Use default database for task storage
    "save_limit": 250,  # Keep last 250 successful tasks in database
    "ack_failures": True,  # Acknowledge failed tasks
    "max_attempts": 1,  # Number of retry attempts for failed tasks
    "cached": False,  # Don't use cache for broker (using ORM)
    "sync": BACKGROUND_DEV,  # Run tasks synchronously in dev, asynchronously in prod
}
