// Every user-visible 2026 string. App chrome ("Save", "Matches") lives in app i18n, not here.
// BETA: the match form wording will change with the form (owner, 2026-10-01).
export const en: Record<string, string> = {
  "game.name": "REBUILT",
  "units.pieces": "fuel",

  // phases
  "phase.pre": "Pre-match",
  "phase.auto": "Auto",
  "phase.teleop": "Teleop",
  "phase.endgame": "Endgame",
  "phase.post": "After the match",
  "period.transition": "Transition",
  "period.shift1": "Shift 1",
  "period.shift2": "Shift 2",
  "period.shift3": "Shift 3",
  "period.shift4": "Shift 4",
  "hint.auto":
    "Watch for: where it starts, what it picks up, and whether it climbs.",
  "hint.endgame":
    "Watch for: when it starts climbing and which level it reaches.",

  // pre
  "pre.noShow": "Robot didn't show up",
  "pre.noShow.help":
    "Turn on if the robot never came onto the field. The rest of the form is skipped.",
  "pre.startZone": "Starting position",
  "pre.startZone.nearTrenchLeft": "Left, by the trench",
  "pre.startZone.nearBumpLeft": "Left, by the bump",
  "pre.startZone.centerHub": "Center, in front of the hub",
  "pre.startZone.nearBumpRight": "Right, by the bump",
  "pre.startZone.nearTrenchRight": "Right, by the trench",
  "pre.preloaded": "Started with fuel",

  // auto
  "auto.moved": "Left the starting line",
  "auto.sources": "Where it got fuel",
  "auto.sources.preload": "Preload",
  "auto.sources.depot": "Depot",
  "auto.sources.outpost": "Outpost",
  "auto.sources.neutralZone": "Neutral zone",
  "auto.sources.none": "None",
  "auto.actions": "What it did",
  "auto.actions.scoredHub": "Scored in the hub",
  "auto.actions.crossedBump": "Crossed the bump",
  "auto.actions.usedTrench": "Used the trench",
  "auto.actions.disruptedOpponent": "Disrupted an opponent",
  "auto.actions.climbed": "Climbed",
  "auto.climb": "Auto climb",
  "auto.climb.none": "No climb",
  "auto.climb.attemptFail": "Tried, failed",
  "auto.climb.level1": "Level 1",
  "auto.effectiveness": "How well did auto go?",
  "auto.effectiveness.low": "Did nothing useful",
  "auto.effectiveness.high": "Flawless, scored a lot",

  // teleop
  "teleop.role": "Main role",
  "teleop.role.offense": "Offense",
  "teleop.role.defense": "Defense",
  "teleop.role.feeder": "Feeder",
  "teleop.role.mixed": "Mixed",
  "teleop.role.idle": "Idle",
  "teleop.scoringRating": "Scoring",
  "teleop.scoringRating.low": "Rarely scored",
  "teleop.scoringRating.high": "Scored constantly",
  "teleop.accuracy": "Accuracy",
  "teleop.accuracy.low": "Misses a lot",
  "teleop.accuracy.mid": "Mostly in",
  "teleop.accuracy.high": "Almost never misses",
  "teleop.inactiveHubBehavior": "While its hub was inactive",
  "teleop.inactiveHubBehavior.collected": "Collected fuel",
  "teleop.inactiveHubBehavior.defended": "Played defense",
  "teleop.inactiveHubBehavior.fed": "Fed partners",
  "teleop.inactiveHubBehavior.waited": "Waited",
  "teleop.inactiveHubBehavior.keptShooting": "Kept shooting (wasted)",
  "teleop.travel": "How it crossed the field",
  "teleop.travel.trench": "Trench",
  "teleop.travel.bump": "Bump",
  "teleop.defenseRating": "Defense",
  "teleop.defenseRating.low": "No effect",
  "teleop.defenseRating.high": "Shut the opponent down",
  "teleop.wasDefended": "Was it defended?",
  "teleop.wasDefended.no": "No",
  "teleop.wasDefended.handledWell": "Handled it well",
  "teleop.wasDefended.struggled": "Struggled",
  "teleop.driverSkill": "Driver skill",
  "teleop.driverSkill.low": "Struggled to drive",
  "teleop.driverSkill.high": "Exceptional driving",
  incidents: "Robot stopped or broke",
  "incidents.help":
    "Log each time the robot stopped working, tipped, got stuck or lost a part.",

  // endgame
  "endgame.climbResult": "Climb",
  "endgame.climbResult.none": "No climb",
  "endgame.climbResult.attemptFail": "Tried, failed",
  "endgame.climbResult.level1": "Level 1",
  "endgame.climbResult.level2": "Level 2",
  "endgame.climbResult.level3": "Level 3",
  "endgame.climbStart": "Started climbing",
  "endgame.climbStart.early": "More than 20 s left",
  "endgame.climbStart.mid": "10–20 s left",
  "endgame.climbStart.late": "Under 10 s left",
  "endgame.climbStart.didntTry": "Didn't try",
  "endgame.keptScoring": "Kept scoring instead of climbing",

  // post
  "post.penalties": "Fouls",
  "post.penalties.none": "None",
  "post.penalties.pinning": "Pinning",
  "post.penalties.protectedZone": "Contact in a protected zone",
  "post.penalties.overBumper": "Over the bumper",
  "post.penalties.tooManyPieces": "Too many pieces",
  "post.penalties.other": "Other",
  "post.strategySwitch": "Changed plan when something went wrong",
  "post.strategySwitch.none": "Didn't need to",
  "post.strategySwitch.adaptedWell": "Adapted well",
  "post.strategySwitch.adaptedPoorly": "Adapted poorly",
  "post.overall": "Overall contribution",
  "post.overall.low": "Hurt the alliance",
  "post.overall.high": "Carried the alliance",
  "post.notes": "Notes",
  "post.notes.tag.fast": "Fast",
  "post.notes.tag.slow": "Slow",
  "post.notes.tag.greatDriver": "Great driver",
  "post.notes.tag.tippy": "Tippy",
  "post.notes.tag.jammed": "Jammed",
  "post.notes.tag.goodPartner": "Good partner",
  "post.notes.tag.aggressive": "Aggressive",
  "post.notes.tag.smartPositioning": "Smart positioning",

  // incidents
  "inc.noMovement": "Stopped moving",
  "inc.stutter": "Cut out or stuttered",
  "inc.mechanism": "Mechanism broke",
  "inc.tipped": "Tipped over",
  "inc.stuck": "Got stuck",
  "inc.bumperOff": "Bumper came off",
  "inc.fieldFault": "Field fault",
  "inc.other": "Something else",
  "inc.category.electrical": "Electrical",
  "inc.category.mechanical": "Mechanical",
  "inc.category.software": "Software",
  "inc.category.driver": "Driver",
  "inc.category.field": "Field",
  "inc.category.unknown": "Not sure",
  "inc.length.brief": "Under 5 s",
  "inc.length.short": "5–15 s",
  "inc.length.long": "Over 15 s",
  "inc.length.restOfMatch": "Rest of the match",
  "inc.resolution.recoveredSelf": "Recovered on its own",
  "inc.resolution.partnerHelped": "A partner helped",
  "inc.resolution.neverRecovered": "Never recovered",
  "inc.resolution.unclear": "Couldn't tell",

  // pit
  "pit.title": "Robot",
  "pit.fitsTrench": "Fits under the trench",
  "pit.crossesBump": "Can cross the bump",
  "pit.capacity": "Fuel it can hold",
  "pit.shooter": "Shooter",
  "pit.shooter.fixed": "Fixed",
  "pit.shooter.adjustableHood": "Adjustable hood",
  "pit.shooter.turret": "Turret",
  "pit.shooter.none": "None",
  "pit.intake": "Intake",
  "pit.intake.overBumper": "Over the bumper",
  "pit.intake.underBumper": "Under the bumper",
  "pit.intake.none": "None",
  "pit.intakeSources": "Picks up fuel from",
  "pit.intakeSources.ground": "Ground",
  "pit.intakeSources.outpost": "Outpost",
  "pit.intakeSources.depot": "Depot",
  "pit.climbMax": "Highest climb",
  "pit.climbMax.none": "Doesn't climb",
  "pit.climbMax.level1": "Level 1",
  "pit.climbMax.level2": "Level 2",
  "pit.climbMax.level3": "Level 3",
  "pit.autoRoutines": "Auto routines",
  "pit.autoRoutines.tag.scores": "Scores",
  "pit.autoRoutines.tag.depot": "Depot",
  "pit.autoRoutines.tag.outpost": "Outpost",
  "pit.autoRoutines.tag.climb": "Climbs",
  "pit.autoRoutines.tag.disrupt": "Disrupts",
  "pit.vision": "Vision",
  "pit.vision.autoAim": "Auto-aim",
  "pit.vision.poseEstimation": "Pose estimation",
  "pit.vision.none": "None",
  "pit.wiringQuality": "Wiring",
  "pit.wiringQuality.low": "Messy or loose",
  "pit.wiringQuality.high": "Clean and strain-relieved",
  "pit.robustness": "Build quality",
  "pit.robustness.low": "Fragile",
  "pit.robustness.high": "Built to take hits",
  "pit.preferredRole": "Preferred role",
  "pit.preferredRole.offense": "Offense",
  "pit.preferredRole.defense": "Defense",
  "pit.preferredRole.feeder": "Feeder",
  "pit.preferredRole.flexible": "Flexible",
  "pit.notes": "Notes",

  // post-scouting (after quals)
  "postScout.title": "After quals",
  "postScout.changesSinceStart": "Changes since the start of the event",
  "postScout.knownIssues": "Known issues",
  "postScout.knownIssues.tag.electrical": "Electrical",
  "postScout.knownIssues.tag.mechanical": "Mechanical",
  "postScout.knownIssues.tag.software": "Software",
  "postScout.knownIssues.tag.none": "None",
  "postScout.repairsDone": "Repairs done",
  "postScout.willingDefense": "Willing to play defense",
  "postScout.willingDefense.yes": "Yes",
  "postScout.willingDefense.preferNot": "Would rather not",
  "postScout.willingDefense.no": "No",
  "postScout.bestRole": "Best role",
  "postScout.bestRole.offense": "Offense",
  "postScout.bestRole.defense": "Defense",
  "postScout.bestRole.feeder": "Feeder",
  "postScout.bestRole.flexible": "Flexible",
  "postScout.climbConfidence": "Climb they trust",
  "postScout.climbConfidence.none": "None",
  "postScout.climbConfidence.level1": "Level 1",
  "postScout.climbConfidence.level2": "Level 2",
  "postScout.climbConfidence.level3": "Level 3",
  "postScout.spareParts": "Has spare parts",
  "postScout.driveTeamNotes": "Drive team notes",
  "postScout.wouldPick": "Would you pick them?",
  "postScout.wouldPick.low": "No",
  "postScout.wouldPick.high": "Definitely",

  // capabilities
  "cap.climbMax": "Climb",
  "cap.fitsTrench": "Trench",
  "cap.crossesBump": "Bump",
  "cap.shooter": "Shooter",

  // metrics
  "metric.reliability": "Reliability",
  "metric.reliability.desc":
    "Share of matches where the robot worked the whole time. Brief stops and field faults don't count.",
  "metric.reliability.badMatches": "Matches with a breakdown",
  "metric.reliability.electrical": "Electrical incidents",
  "metric.consistency": "Consistency",
  "metric.consistency.desc":
    "How evenly it performs from match to match, from the scoring and auto ratings.",
  "metric.consistency.composite": "Average rating",
  "metric.defense": "Defense",
  "metric.defense.desc":
    "Average defense rating in matches where it played defense.",
  "metric.defense.rate": "Matches on defense",
  "metric.autoEffectiveness": "Auto",
  "metric.autoEffectiveness.desc":
    "Average auto rating, lowered by auto breakdowns.",
  "metric.autoEffectiveness.incidentRate": "Auto breakdown rate",
  "metric.autoEffectiveness.climbRate": "Auto climb rate",

  // presentation
  "col.epa": "EPA",
  "col.autoScoring": "Auto fuel",
  "prematch.overview": "Overview",
  "summary.auto": "Auto",
  "summary.scoring": "Scoring",
  "summary.climb": "Climb",
  "summary.stops": "Stops",
  "breakdown.autoPoints": "Auto",
  "breakdown.teleopPoints": "Teleop",
  "breakdown.endgamePoints": "Endgame",
  "breakdown.foulPoints": "Fouls",
  "breakdown.rp": "Ranking points",
  "breakdown.piecesScored": "Fuel scored",
  "prematch.capabilities": "What it can do",
}
